# Generated by Django 4.0.3 on 2023-03-16 02:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_rest', '0013_alter_user_host_status_alter_user_is_superhost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='max_guests',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='rental_type',
            field=models.CharField(blank=True, default='Entire Place', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='!WwPz5Uevvk3l5H9z2LjWHekCFbHpAdFQ2YyDzlnQ', max_length=128),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('rating', models.FloatField(blank=True, default=5.0, null=True)),
                ('comment', models.TextField(blank=True, default='', null=True)),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='user_rest.rental')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bedroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bedrooms', to='user_rest.rental')),
            ],
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_type', models.CharField(max_length=255)),
                ('bed_count', models.IntegerField(blank=True, default=1, null=True)),
                ('bedroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='user_rest.bedroom')),
            ],
        ),
    ]
