# Generated by Django 4.0.3 on 2023-03-16 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_rest', '0014_rental_max_guests_rental_rental_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='bath_count',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='!6O6b58uxuX8eWbQQ6XCiO9HcJx0A60O71GdHtbP4', max_length=128),
        ),
    ]
