# Generated by Django 4.0.3 on 2023-03-16 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_rest', '0015_rental_bath_count_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='description',
            field=models.CharField(blank=True, default='Large, modern home situated on a breathtaking property carved out of the hillside. Amazing views from all over the property, with expansive outdoor space that includes a hot tub and a pool.  Close to Oakhurst, Bass Lake, and Yosemite High speed Wi Fi Dedicated work space The space Almost new home, modern home on a large property. Secluded, yet close to town and Yosemite. Large house with high ceilings and great views from most rooms.', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='!J4v2uvL2CKIB3yrHUHQUSZMdK3Q0oNUdoOB0OVqi', max_length=128),
        ),
    ]
