# Generated by Django 4.0.3 on 2023-03-16 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_rest', '0016_rental_description_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='price_before_discount',
            field=models.IntegerField(blank=True, default=221, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='price_per_night',
            field=models.IntegerField(blank=True, default=169, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='!MyDV2YHRktuxLleOo2SSouZWSsbO0cBxn7ohMNN2', max_length=128),
        ),
    ]
