# Generated by Django 4.0.3 on 2023-03-16 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_rest', '0017_rental_price_before_discount_rental_price_per_night_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='!I08g3UA5dVjVeFm5hbVHe7Z1DLfJAnMkdvUkqOmW', max_length=128),
        ),
    ]
