# Generated by Django 4.0.3 on 2023-03-16 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_rest', '0018_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='!jXlzZ48CONRUhh1DFQjfsxvfSdirGnpRZjsIbyz1', max_length=128),
        ),
    ]
