# Generated by Django 4.0.3 on 2023-03-16 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_rest', '0020_rental_images_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='images',
            field=models.TextField(blank=True, default='["https://a0.muscache.com/im/pictures/miso/Hosting-745787028816952393/original/2b38eb6e-0b90-4c5f-aa30-0636b0610b51.jpeg?im_w=720"]', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='!pyRmPicYYtsmNbVV1v1eYgitl2hay9DhMch7rzKS', max_length=128),
        ),
    ]
