# Generated by Django 4.0.3 on 2023-03-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_rest', '0021_alter_rental_images_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='description',
            field=models.TextField(blank=True, default='Large, modern home situated on a breathtaking property carved out of the hillside. Amazing views from all over the property, with expansive outdoor space that includes a hot tub and a pool.  Close to Oakhurst, Bass Lake, and Yosemite High speed Wi Fi Dedicated work space The space Almost new home, modern home on a large property. Secluded, yet close to town and Yosemite. Large house with high ceilings and great views from most rooms.', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='!BZkE7kOxuCtiOhdaXBHTQVZlXIvLYGOTymoJRXVk', max_length=128),
        ),
    ]
